draw_background_ext(bgAM2RTitle, oControl.mod_xcoordinate, oControl.mod_ycoordinate, 1, 1, 0, -1, image_alpha)
draw_set_alpha(image_alpha)
draw_rectangle_colour((234 + (oControl.widescreen_space / 2)), 224, (320 + (oControl.widescreen_space / 2)), 231, c_black, c_black, c_black, c_black, 0)
draw_set_alpha(1)
draw_set_font(global.fontMenuSmall)
draw_set_halign(fa_right)
draw_text_colour((320 + (oControl.widescreen_space / 2)), 221, "reddit.com/r/AM2R", $23BC8E, $23BC8E, $23BC8E, $23BC8E, image_alpha)
draw_set_halign(fa_left)
draw_background_ext(bgURL, (198 + (oControl.widescreen_space / 2)), 232, 1, 1, 0, -1, image_alpha)
draw_set_valign(fa_top)
draw_set_font(fontMenuTinyDefault)
draw_background_ext(bgVersion, (0 - (oControl.widescreen_space / 2)), 0, (string_width("AM2R 1.5.5") + 1), 1, 0, -1, image_alpha)
draw_text_colour((1 - (oControl.widescreen_space / 2)), versionoffsety, "AM2R 1.5.5", $23BC8E, $23BC8E, $23BC8E, $23BC8E, image_alpha)
draw_set_font(fontMenuTinyDefault)
draw_background_ext(bgVersion, (0 - (oControl.widescreen_space / 2)), 8, (string_width("Multitroid 1.3") + 1), 1, 0, -1, image_alpha)
draw_text_colour((1 - (oControl.widescreen_space / 2)), (versionoffsety + 8), "Multitroid 1.3", $23BC8E, $23BC8E, $23BC8E, $23BC8E, image_alpha)
draw_set_font(fontMenuTinyDefault)
draw_background_ext(bgVersion, (0 - (oControl.widescreen_space / 2)), 16, (string_width(hordeversion) + 1), 1, 0, -1, image_alpha)
draw_text_colour((1 - (oControl.widescreen_space / 2)), (versionoffsety + 16), hordeversion, $23BC8E, $23BC8E, $1EBFC1, $1EBFC1, image_alpha)
