hp = 10
damage = 40
hpush = -5
vpush = -4
hurt = 0
state = 1
statetime = 0
GRAB = 0
GRABtime = 0
flashing = 0
fxtimer = 0
startx = x
starty = y
targetx = (oCharacter.x + 2)
targety = (oCharacter.y - 16)
endx = 7
endy = -3
eatx = (oHordeBreeder.x - 8)
eaty = (oHordeBreeder.y - 32)
stlx = x
stly = (y - 4)
strx = startx
stry = (starty - 4)
sbrx = startx
sbry = (starty + 4)
sblx = x
sbly = (y + 4)
image_speed = 0
GRABfx = 0
eat = 0
reel = 0
visible = false
xtreme = oControl.mod_monstersextremecheck
